version: "3"

services:
  web:
    build: .
    command: [ "bin/rails", "s", "-b", "0.0.0.0" ]
    volumes:
      - .:/root/app
    ports:
      - "3000:3000"
      - "9292:9292"
  postgres:
    image: "postgres:14"
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  # mysql:
  #   image: "mysql:8.0"
  #   command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   platform: linux/amd64
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #   ports:
  #     - "3307:3306"
  redis:
    image: redis:5
    ports:
      - "6379:6379"
  mailhog:
    image: mailhog/mailhog
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: ./tmp/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
